### ISSUE TITLE
Can't reach custom characters.

### ISSUE THREAD

**Issue by catte-cloud** [pepperpow/smb2-door-randomizer#1]
![image](https://user-images.githubusercontent.com/78244937/132074412-117192a6-1c2c-4ea5-b812-039472ddefaf.png)

Cannot reach custom characters due to my screens resolution, can you possibly add a scroll bar in this menu? thank you!

**Comment by pepperpow** [comment]
Will try to fix this soon!

**Comment by pepperpow** [comment]
This should be fixed in the latest.
