### ISSUE TITLE
Game Crash?

### ISSUE THREAD

**Issue by PheonixMMKC777** [pepperpow/smb2-door-randomizer#2]
Game Softlocked upon beating the flying bird face boss.
It still plays the music but the graphics are froze.
image link: https://ibb.co/pf6122Q

Seed: F3MDXZWBLB
20 Level mode (Basic)

**Comment by pepperpow** [comment]
Oh it must not have put a boss at the end.  I haven't tested a full 7
world's I'm sorry, I have to do all the bug testing myself, but I'll fix it
thank you!!

**Comment by pepperpow** [comment]
This should be fixed in some form.
